// ============================================================================
// database.types.ts
//
// This file does NOT run any code. It only describes SHAPES (TypeScript
// "types") of the tables in your Supabase database, so that when you write
// `supabase.from("products").select(...)` elsewhere in the app, TypeScript
// knows exactly which columns exist, what type each one is, and warns you
// if you make a typo like "prodcut_name".
//
// It is written by hand here to match the SQL you ran in Supabase. If you
// ever add/remove a column in Supabase, you must update this file to match,
// or TypeScript's picture of your database will be wrong.
// ============================================================================

// A "type" is a custom named shape. Here we say a UserRole can ONLY ever be
// one of these three exact strings — nothing else. This mirrors the Postgres
// `user_role` enum you created with `create type user_role as enum (...)`.
export type UserRole = "customer" | "admin" | "manager";

// Every table that has a foreign key (like reviews.product_id pointing to
// products.id) can describe that link here. We're not using Supabase's
// auto-generated relationship metadata, so we just say "an array of these,
// but it's fine if it's empty" — hence Relationship[] and not requiring any
// entries below.
type Relationship = {
  foreignKeyName: string;       // Postgres's internal name for the FK constraint
  columns: string[];            // which column(s) on THIS table hold the FK
  isOneToOne?: boolean;         // "?" means optional — true if it's a 1:1 relation
  referencedRelation: string;   // the table being pointed to
  referencedColumns: string[];  // which column(s) on THAT table are referenced
};

// `export` makes this type importable in other files via
// `import type { Database } from "./database.types"`.
// The Supabase client library (createBrowserClient<Database>(...)) uses this
// type as a generic parameter so every `.from("table_name")` call is typed.
export type Database = {
  // Recent versions of @supabase/postgrest-js require this exact key to
  // exist so the library knows which version of its own types to use
  // internally. You don't need to understand this deeply — just keep it.
  __InternalSupabase: {
    PostgrestVersion: "13";
  };

  // Supabase organizes tables into "schemas". Almost everything you create
  // through the Table Editor lives in the "public" schema by default.
  public: {
    // "Tables" lists every table in the public schema, and for each table,
    // three shapes:
    //   Row    -> what a row looks like when you SELECT it (all columns,
    //             including ones with defaults like `id` and `created_at`)
    //   Insert -> what you're allowed to pass when you INSERT a new row
    //             (columns with a database default, like `id` or
    //             `created_at`, become optional here — marked with "?")
    //   Update -> what you're allowed to pass when you UPDATE a row
    //             (everything is optional, since you usually only change
    //             one or two fields at a time)
    Tables: {
      // ---- profiles table -------------------------------------------
      // Extends Supabase's built-in auth.users table with app-specific
      // fields (name, phone, role). One row per signed-up user.
      profiles: {
        Row: {
          id: string;              // uuid, matches auth.users.id (the login account)
          name: string;            // display name, required (no "| null")
          phone: string | null;    // optional phone number, can be null in the DB
          role: UserRole;          // one of "customer" | "admin" | "manager"
          created_at: string;      // timestamp, sent back as an ISO date string
          updated_at: string;      // timestamp, updates whenever the row changes
        };
        Insert: {
          // When inserting, `id` MUST be provided (it has to match the
          // auth.users id — there's no default that generates it for you here).
          id: string;
          name: string;
          // The "?" means this key can be left out entirely when inserting;
          // Postgres will use its column default or NULL instead.
          phone?: string | null;
          role?: UserRole; // defaults to 'customer' in the database if omitted
        };
        Update: {
          // Every field is optional on update — you only send what changed.
          name?: string;
          phone?: string | null;
          role?: UserRole;
        };
        Relationships: Relationship[];
      };

      // ---- products table ---------------------------------------------
      products: {
        Row: {
          id: string;                       // uuid, auto-generated by the DB
          name: string;                     // product display name
          slug: string;                     // URL-friendly identifier, e.g. "red-velvet-cake"
          description: string | null;
          price: number;                    // numeric in Postgres, comes through as a JS number
          category: string;
          flavor: string | null;
          weight: string | null;
          ingredients: string[] | null;     // Postgres array of text -> JS string array
          thumbnail_url: string | null;
          featured: boolean;
          popular: boolean;
          in_stock: boolean;
          rating: number;
          review_count: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;        // soft-delete marker; null = not deleted
        };
        Insert: {
          id?: string;             // optional: DB generates a uuid if you omit it
          name: string;            // required: no default value exists
          slug: string;            // required: must be unique, you must supply it
          description?: string | null;
          price?: number;          // optional: defaults to 0 in the DB
          category: string;        // required
          flavor?: string | null;
          weight?: string | null;
          ingredients?: string[] | null;
          thumbnail_url?: string | null;
          featured?: boolean;      // optional: defaults to false
          popular?: boolean;
          in_stock?: boolean;      // optional: defaults to true
        };
        Update: {
          name?: string;
          slug?: string;
          description?: string | null;
          price?: number;
          category?: string;
          flavor?: string | null;
          weight?: string | null;
          ingredients?: string[] | null;
          thumbnail_url?: string | null;
          featured?: boolean;
          popular?: boolean;
          in_stock?: boolean;
          deleted_at?: string | null; // set this to "soft delete" a product
        };
        Relationships: Relationship[];
      };

      // ---- product_images table ---------------------------------------
      // One product can have many images (a 1-to-many relationship).
      product_images: {
        Row: {
          id: string;
          product_id: string; // uuid pointing back at products.id
          url: string;
          sort_order: number; // controls the display order of the gallery
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string; // required: every image must belong to a product
          url: string;        // required
          sort_order?: number; // optional: defaults to 0
        };
        Update: {
          product_id?: string;
          url?: string;
          sort_order?: number;
        };
        Relationships: Relationship[];
      };

      // ---- reviews table ------------------------------------------------
      reviews: {
        Row: {
          id: string;
          product_id: string;  // which product this review is about
          user_id: string;     // which profile wrote it
          rating: number;      // 1-5, enforced by a CHECK constraint in Postgres
          comment: string;
          approved: boolean;   // admin must approve before it's shown publicly
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          product_id: string;
          user_id: string;
          rating: number;
          comment: string;
          approved?: boolean; // optional: defaults to false (needs admin approval)
        };
        Update: {
          rating?: number;
          comment?: string;
          approved?: boolean; // admins flip this to true to publish the review
          deleted_at?: string | null;
        };
        Relationships: Relationship[];
      };

      // ---- general_feedback table ---------------------------------------
      // Site-wide feedback (not tied to a specific product), e.g. from a
      // "Leave us feedback" page.
      general_feedback: {
        Row: {
          id: string;
          user_id: string;
          comment: string;
          reply: string | null; // an admin can write a public reply
          approved: boolean;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          comment: string;
          reply?: string | null;
          approved?: boolean;
        };
        Update: {
          comment?: string;
          reply?: string | null;
          approved?: boolean;
          deleted_at?: string | null;
        };
        Relationships: Relationship[];
      };

      // ---- hero table ---------------------------------------------------
      // A "singleton" table — it only ever has ONE row (id is always 1,
      // enforced by a `check (id = 1)` constraint in the SQL). Used to store
      // the editable homepage banner content.
      hero: {
        Row: {
          id: number;
          title: string;
          subtitle: string | null;
          image_url: string | null;
          button_text: string | null;
          button_link: string | null;
          updated_at: string;
        };
        Insert: {
          id?: number;    // optional: defaults to 1
          title: string;
          subtitle?: string | null;
          image_url?: string | null;
          button_text?: string | null;
          button_link?: string | null;
        };
        Update: {
          title?: string;
          subtitle?: string | null;
          image_url?: string | null;
          button_text?: string | null;
          button_link?: string | null;
        };
        Relationships: Relationship[];
      };

      // ---- notices table --------------------------------------------------
      // Banner-style site notices, e.g. "Closed for Christmas". Can have a
      // start/end time window and an "active" toggle.
      notices: {
        Row: {
          id: string;
          message: string;
          active: boolean;
          starts_at: string | null;
          ends_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          message: string;
          active?: boolean; // optional: defaults to true
          starts_at?: string | null;
          ends_at?: string | null;
        };
        Update: {
          message?: string;
          active?: boolean;
          starts_at?: string | null;
          ends_at?: string | null;
        };
        Relationships: Relationship[];
      };

      // ---- discounts table --------------------------------------------------
      discounts: {
        Row: {
          id: string;
          title: string;
          code: string;       // the coupon code customers type in, e.g. "SWEET10"
          percentage: number; // 1-100, enforced by a CHECK constraint
          expiry: string;     // a plain date (no time), e.g. "2026-12-31"
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          code: string;
          percentage: number;
          expiry: string;
        };
        Update: {
          title?: string;
          code?: string;
          percentage?: number;
          expiry?: string;
        };
        Relationships: Relationship[];
      };

      // ---- cake_templates table -----------------------------------------
      // Saved designs from the 3D cake builder tool.
      cake_templates: {
        Row: {
          id: string;
          user_id: string | null; // nullable: a guest could design one before logging in
          shape: string;
          levels: number;
          layers: number;
          flavor: string | null;
          cream: string | null;
          color: string | null;
          decoration: string | null;
          topping: string | null;
          screenshot_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          shape: string;
          levels: number;
          layers: number;
          flavor?: string | null;
          cream?: string | null;
          color?: string | null;
          decoration?: string | null;
          topping?: string | null;
          screenshot_url?: string | null;
        };
        Update: {
          shape?: string;
          levels?: number;
          layers?: number;
          flavor?: string | null;
          cream?: string | null;
          color?: string | null;
          decoration?: string | null;
          topping?: string | null;
          screenshot_url?: string | null;
        };
        Relationships: Relationship[];
      };

      // ---- settings table -------------------------------------------------
      // Another "singleton" table (id always 1) — global shop settings like
      // business name, WhatsApp number, opening hours, shown across the site.
      settings: {
        Row: {
          id: number;
          business_name: string;
          phone: string | null;
          email: string | null;
          whatsapp_number: string;
          opening_hours: string | null;
          address: string | null;
          logo_url: string | null;
        };
        Insert: {
          id?: number;
          business_name: string;
          phone?: string | null;
          email?: string | null;
          whatsapp_number: string;
          opening_hours?: string | null;
          address?: string | null;
          logo_url?: string | null;
        };
        Update: {
          business_name?: string;
          phone?: string | null;
          email?: string | null;
          whatsapp_number?: string;
          opening_hours?: string | null;
          address?: string | null;
          logo_url?: string | null;
        };
        Relationships: Relationship[];
      };
    };

    // We don't use any database VIEWS (a "view" is a saved SQL query that
    // acts like a virtual read-only table), so this is just an empty
    // placeholder. `Record<string, never>` means "an object where every
    // possible key maps to a value that can never actually exist" — i.e.
    // effectively empty, but still satisfies the shape the library expects.
    Views: Record<string, never>;

    // Postgres FUNCTIONS you can call through the Supabase client via
    // `supabase.rpc("function_name")`. Your RLS policies use a Postgres
    // function called `is_admin()` internally, but you don't call it
    // directly from the frontend — this entry documents it for completeness.
    Functions: {
      is_admin: {
        Args: Record<string, never>; // it takes no arguments
        Returns: boolean;
      };
    };

    // Maps Postgres ENUM types to their TypeScript equivalents.
    Enums: {
      user_role: UserRole;
    };

    // We don't use any custom Postgres composite types, so again this is
    // just an empty placeholder to satisfy the required shape.
    CompositeTypes: Record<string, never>;
  };
};